package com.xqls.base.dao;

import com.xqls.base.entity.UserInfo;
import com.xqls.base.entity.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_info (id, username, ",
        "password, status, ",
        "enterprise_id, name, ",
        "gender, birth, empy, ",
        "email, mobile, createid, ",
        "createdatatime, delflag, ",
        "companycode, idcard, ",
        "imgurl, departmen, ",
        "dicode, signmenu)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{enterpriseId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{gender,jdbcType=VARCHAR}, #{birth,jdbcType=VARCHAR}, #{empy,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, #{createid,jdbcType=DECIMAL}, ",
        "#{createdatatime,jdbcType=TIMESTAMP}, #{delflag,jdbcType=VARCHAR}, ",
        "#{companycode,jdbcType=VARCHAR}, #{idcard,jdbcType=VARCHAR}, ",
        "#{imgurl,jdbcType=VARCHAR}, #{departmen,jdbcType=INTEGER}, ",
        "#{dicode,jdbcType=VARCHAR}, #{signmenu,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=true, resultType=Integer.class)
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    List<UserInfo> list(UserInfo userInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, username, password, status, enterprise_id, name, gender, birth, empy, email, ",
        "mobile, createid, createdatatime, delflag, companycode, idcard, imgurl, departmen, ",
        "dicode, signmenu",
        "from user_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    @Update({
        "update user_info",
        "set username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "enterprise_id = #{enterpriseId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=VARCHAR},",
          "birth = #{birth,jdbcType=VARCHAR},",
          "empy = #{empy,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "createid = #{createid,jdbcType=DECIMAL},",
          "createdatatime = #{createdatatime,jdbcType=TIMESTAMP},",
          "delflag = #{delflag,jdbcType=VARCHAR},",
          "companycode = #{companycode,jdbcType=VARCHAR},",
          "idcard = #{idcard,jdbcType=VARCHAR},",
          "imgurl = #{imgurl,jdbcType=VARCHAR},",
          "departmen = #{departmen,jdbcType=INTEGER},",
          "dicode = #{dicode,jdbcType=VARCHAR},",
          "signmenu = #{signmenu,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserInfo record);
}