package com.xqls.base.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birth
     *
     * @mbggenerated
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.empy
     *
     * @mbggenerated
     */
    private String empy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.createid
     *
     * @mbggenerated
     */
    private Long createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.createdatatime
     *
     * @mbggenerated
     */
    private Date createdatatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.delflag
     *
     * @mbggenerated
     */
    private String delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.companycode
     *
     * @mbggenerated
     */
    private String companycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.imgurl
     *
     * @mbggenerated
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.departmen
     *
     * @mbggenerated
     */
    private Integer departmen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.dicode
     *
     * @mbggenerated
     */
    private String dicode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.signmenu
     *
     * @mbggenerated
     */
    private String signmenu;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    public UserInfo(Integer id, String username, String password, String status, Integer enterpriseId, String name, String gender, String birth, String empy, String email, String mobile, Long createid, Date createdatatime, String delflag, String companycode, String idcard, String imgurl, Integer departmen, String dicode, String signmenu) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.status = status;
        this.enterpriseId = enterpriseId;
        this.name = name;
        this.gender = gender;
        this.birth = birth;
        this.empy = empy;
        this.email = email;
        this.mobile = mobile;
        this.createid = createid;
        this.createdatatime = createdatatime;
        this.delflag = delflag;
        this.companycode = companycode;
        this.idcard = idcard;
        this.imgurl = imgurl;
        this.departmen = departmen;
        this.dicode = dicode;
        this.signmenu = signmenu;
    }

    public UserInfo() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.username
     *
     * @return the value of user_info.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.enterprise_id
     *
     * @return the value of user_info.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birth
     *
     * @return the value of user_info.birth
     *
     * @mbggenerated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.empy
     *
     * @return the value of user_info.empy
     *
     * @mbggenerated
     */
    public String getEmpy() {
        return empy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mobile
     *
     * @return the value of user_info.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.createid
     *
     * @return the value of user_info.createid
     *
     * @mbggenerated
     */
    public Long getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.createdatatime
     *
     * @return the value of user_info.createdatatime
     *
     * @mbggenerated
     */
    public Date getCreatedatatime() {
        return createdatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.delflag
     *
     * @return the value of user_info.delflag
     *
     * @mbggenerated
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.companycode
     *
     * @return the value of user_info.companycode
     *
     * @mbggenerated
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.idcard
     *
     * @return the value of user_info.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.imgurl
     *
     * @return the value of user_info.imgurl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.departmen
     *
     * @return the value of user_info.departmen
     *
     * @mbggenerated
     */
    public Integer getDepartmen() {
        return departmen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.dicode
     *
     * @return the value of user_info.dicode
     *
     * @mbggenerated
     */
    public String getDicode() {
        return dicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.signmenu
     *
     * @return the value of user_info.signmenu
     *
     * @mbggenerated
     */
    public String getSignmenu() {
        return signmenu;
    }
}